[package]
name = "stg-rs"
version = "0.1.0"
authors = ["wasabi315 <wasabi.nvim.st@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty = "0.10.0"
