[package]
name = "stg-rs"
version = "0.1.0"
authors = ["wasabi315 <wasabi.nvim.st@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
pretty = "0.10.0"
once_cell = "1.8.0"
